#!/usr/bin/env sh

# All the credits go to bs-let: https://github.com/reasonml-labs/bs-let/blob/master/ppx

ROOT="$(dirname "$0")/.."
OS="$(uname)"

echo $ROOT
echo $OS

if [ "$OS" = "Darwin" ]; then
  cp "${ROOT}/binaries/ppx-osx.exe" "${ROOT}/lenses-ppx"
elif [ "$OS" = "Linux" ]; then
  cp "${ROOT}/binaries/ppx-linux.exe" "${ROOT}/lenses-ppx"
else
  echo "Os not supported"
  exit 1
fi
